### ISSUE TITLE
Where to require purl

### ISSUE THREAD

**Issue by gerbz** [azayarni/purl#2]
Forgive the noob question... 
I'm working to integrate purl into various 3rd party libraries.  
Where do I need to "require" purl in the following case? 1, 2 or 3?

```
// #1
class theClass {
    // #2
    private static function make_request($stuff){       
        // #3       
        $ch = curl_init();      
    }
}
```

**Comment by azayarni** [comment]
Before the class definition in this case. However if you do have any common file (index.php etc), would be better to put it there once for all the libraries. Do you use any framework?

**Comment by gerbz** [comment]
Yeah I have better places to include it, I just thought there may be a scope issue placing it outside the class.
